name: Momentum Lab
description: At Carnegie Mellon University
url: <URL>

markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "deploy.sh"
  - "ghp_deploy.sh"
